version: "3.7"
services:
  api:
    build: "/mnt/c/Users/CaetanoBernal/desktop/docker_compose_final/api"
    container_name: predictapi
    restart: always
    ports:
      - "8000:8000"
  
  streamlit:
    build: "/mnt/c/Users/CaetanoBernal/desktop/docker_compose_final/st_app"
    container_name: ml_streamlit_app
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - api